# credit to: https://dev.to/joshduffney/deploy-ansible-with-github-actions-2f3d  
name: 'Ansible'
description: 'Runs an Ansible playbook'
inputs:
  playbook:
    description: 'Ansible playbook to run'
    required: true
    default: main.yml
  inventory:
    description: 'Ansible inventory to use'
    required: true
    default: localhost
runs:
  using: 'docker'
  image: dsmith73/github-action.ubuntu-ansible:latest
  args:
    - ${{ inputs.playbook }}
    - ${{ inputs.inventory }}
    
