---
# playbook to replace using scheduled tasks on a personal computer  
# and enable moving the update into github with Actions  

- hosts: localhost
  gather_facts: false
  tasks:
  - name: include vars from file
    include_vars: vars.yml

  # This portion of the play is to enable using Secrets in github + actions  
  - name: "get secrets and put them into vars"  
    set_fact:
      DOMAINS     : ${{ secrets.DOMAINS }}
      IP_ADDRESS  : ${{ secrets.IP_ADDRESS }}
      TOKEN       : ${{ secrets.TOKEN }}
  ## End of script customization for github  
  
  - name          : "Update {{ DOMAINS }} on DuckDNS to use {{ IP_ADDRESS }}"
    uri           : 
      url         : "https://{{ BASE_URL }}domains={{ DOMAINS }}&token={{ TOKEN }}&ip={{ IP_ADDRESS }}"
    register      : output

  ## Show the output  
  - name: "Result?"
    debug:
      ## OK = Success / KO = Fail
      msg: "DuckDNS said: {{ (output.msg | regex_findall('(\\w+)\\s'))[0] }}"
