---
# playbook to replace using scheduled tasks on a personal computer  
# and enable moving the update into github with Actions  

- hosts: localhost
  gather_facts: false
  tasks:
  - name: include vars from file
    include_vars: vars.yml
  
  - name          : "Update DuckDNS"
    uri           : 
      url         : "https://{{ BASE_URL }}domains={{ env.DOMAINS }}&token={{ env.TOKEN }}&ip={{ env.IP_ADDRESS }}"
    register      : output

  ## Show the output  
  - name: "Result?"
    debug:
      ## OK = Success / KO = Fail
      msg: "DuckDNS said: {{ (output.msg | regex_findall('(\\w+)\\s'))[0] }}"
