name: "Update DuckDNS on schedule"

on:
  schedule:
    # Uses UTC time (EST - 5)  
    # To run at 2pm every day, set cron to '0 19 * * *'  
#     - cron:  '26 0/6 * * *'
    - cron:  '29 12 * * *'

jobs:
  scheduled:
    name: Scheduled Job
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name: Lint Ansible Playbook
      # Using ansible-community lint to overcome a breaking change  
      uses: ansible/ansible-lint-action@master
      with:
        # This override should be forward compatable  
        override-deps: |
          ansible>=2.9
          ansible-lint>5.3.0
        targets: ""
  deployAnsible:
    needs: scheduled
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/ansible
      with:
        playbook: main.yml
        inventory: localhost
      env:
        DOMAINS: ${{ secrets.DOMAINS }}
        IP_ADDRESS: ${{ secrets.IP_ADDRESS }}
        TOKEN: ${{ secrets.TOKEN }}
