name: "Update DuckDNS on schedule"

on:
  schedule:
    # Uses UTC time (EST - 5)  
    # To run at 2pm every day, set cron to '0 19 * * *'  
    - cron:  '09 18 * * *'

jobs:
  scheduled:
    name: Scheduled Job
    runs-on: ubuntu-latest
    steps:
#     - name: set to EST
#       uses: szenius/set-timezone@v1.0
#       with:
#         timezoneLinux: "EST"
    - name: checkout repo
      uses: actions/checkout@v2
    - name: Lint Ansible Playbook
      uses: ansible-community/ansible-lint-action@master
      with:
        override-deps: |
          ansible>=2.9
          ansible-lint>5.3.0
        targets: ""
  deployAnsible:
    needs: scheduled
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/ansible
      with: 
        playbook: main.yml
        inventory: localhost
        
